### PR TITLE
updated logrus so Prometheus can build on Solaris/Illumos

### PR DESCRIPTION
**Pull request by fazalmajid**
The logrus vendored with Prometheus is ancient, and does not compile on Solaris:

```
tsurumah ~/go>env GOPATH=`pwd` GO15VENDOREXPERIMENT=1 go get -f -t -u -v github.com/prometheus/prometheus/cmd/...
github.com/prometheus/prometheus (download)
github.com/prometheus/prometheus/vendor/github.com/Sirupsen/logrus
# github.com/prometheus/prometheus/vendor/github.com/Sirupsen/logrus
src/github.com/prometheus/prometheus/vendor/github.com/Sirupsen/logrus/text_formatter.go:28: undefined: IsTerminal

```

Updating to the head for logrus fixes the problem.

See also #2732 and https://github.com/sirupsen/logrus/commits/master/terminal_solaris.go

### CODE REVIEW

File: vendor/vendor.json [hunk 1]
```diff
@@ -59,6 +59,12 @@
 			"revisionTime": "2016-09-30T00:14:02Z"
 		},
 		{
+			"checksumSHA1": "DYv6Q1+VfnUVxMwvk5IshAClLvw=",
```
Comment (juliusv) [inline vendor/vendor.json]: Huh weird, I wonder why it wasn't in here (with the old verison) before. Someone must've added it without govendor or something.

**Comment by juliusv** [comment]
:+1:

File: vendor/vendor.json (hunk 1 above)
Comment (fazalmajid) [inline vendor/vendor.json]: Yes, I was wondering about that as well, but put it down to my own lack of experience with govendor. That would also explain why the version bundled was over 2 years old, since that's about how long ago logrus gained Solaris support.

**Comment by fazalmajid** [comment]
I can confirm the Prometheus master branch builds with Go 1.8.1 on OpenIndiana 151a:

```
tsurumah ~/go>env GOPATH=`pwd` GO15VENDOREXPERIMENT=1 go get -f -t -u -v github.com/prometheus/prometheus/cmd/...
github.com/prometheus/prometheus (download)
github.com/prometheus/prometheus/vendor/golang.org/x/sys/unix
github.com/prometheus/prometheus/vendor/github.com/Azure/go-autorest/autorest/to
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/client/metadata
github.com/prometheus/prometheus/vendor/github.com/mailru/easyjson/buffer
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/selection
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/version
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/rand
github.com/prometheus/prometheus/vendor/k8s.io/client-go/util/clock
github.com/prometheus/prometheus/vendor/k8s.io/client-go/util/integer
github.com/prometheus/prometheus/vendor/github.com/asaskevich/govalidator
github.com/prometheus/prometheus/vendor/github.com/beorn7/perks/quantile
github.com/prometheus/prometheus/vendor/github.com/golang/protobuf/proto
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/model
github.com/prometheus/prometheus/vendor/github.com/prometheus/procfs
github.com/prometheus/prometheus/vendor/gopkg.in/yaml.v2
github.com/prometheus/prometheus/vendor/github.com/Azure/go-autorest/autorest
github.com/prometheus/prometheus/vendor/github.com/Azure/go-autorest/autorest/date
github.com/prometheus/prometheus/vendor/github.com/dgrijalva/jwt-go
github.com/prometheus/prometheus/vendor/github.com/Azure/go-autorest/autorest/validation
github.com/prometheus/prometheus/util/strutil
github.com/prometheus/prometheus/vendor/golang.org/x/net/context
github.com/prometheus/prometheus/vendor/github.com/hashicorp/go-cleanhttp
github.com/prometheus/prometheus/vendor/github.com/hashicorp/serf/coordinate
github.com/prometheus/prometheus/vendor/github.com/miekg/dns
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/awserr
github.com/prometheus/prometheus/vendor/github.com/go-ini/ini
github.com/prometheus/prometheus/vendor/github.com/jmespath/go-jmespath
github.com/prometheus/prometheus/vendor/github.com/hashicorp/consul/api
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/endpoints
github.com/prometheus/prometheus/vendor/gopkg.in/fsnotify.v1
github.com/prometheus/prometheus/vendor/golang.org/x/oauth2/internal
github.com/prometheus/prometheus/vendor/golang.org/x/oauth2/jws
github.com/prometheus/prometheus/vendor/golang.org/x/net/context/ctxhttp
github.com/prometheus/prometheus/vendor/github.com/Sirupsen/logrus
github.com/prometheus/prometheus/vendor/google.golang.org/cloud/internal
github.com/prometheus/prometheus/vendor/github.com/Azure/go-autorest/autorest/azure
github.com/prometheus/prometheus/vendor/google.golang.org/api/googleapi/internal/uritemplates
github.com/prometheus/prometheus/vendor/github.com/golang/glog
github.com/prometheus/prometheus/vendor/golang.org/x/oauth2
github.com/prometheus/prometheus/vendor/google.golang.org/cloud/compute/metadata
github.com/prometheus/prometheus/vendor/google.golang.org/api/googleapi
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/log
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/credentials
github.com/prometheus/prometheus/vendor/google.golang.org/api/gensupport
github.com/prometheus/prometheus/vendor/golang.org/x/oauth2/jwt
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/runtime
github.com/prometheus/prometheus/vendor/github.com/emicklei/go-restful/log
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws
github.com/prometheus/prometheus/vendor/github.com/Azure/azure-sdk-for-go/arm/compute
github.com/prometheus/prometheus/vendor/github.com/Azure/azure-sdk-for-go/arm/network
github.com/prometheus/prometheus/vendor/github.com/emicklei/go-restful
github.com/prometheus/prometheus/vendor/github.com/mailru/easyjson/jlexer
github.com/prometheus/prometheus/vendor/golang.org/x/oauth2/google
github.com/prometheus/prometheus/vendor/github.com/mailru/easyjson/jwriter
github.com/prometheus/prometheus/vendor/google.golang.org/api/compute/v1
github.com/prometheus/prometheus/vendor/github.com/PuerkitoBio/urlesc
github.com/prometheus/prometheus/vendor/golang.org/x/net/idna
github.com/prometheus/prometheus/vendor/golang.org/x/text/internal/tag
github.com/prometheus/prometheus/vendor/golang.org/x/text/transform
github.com/prometheus/prometheus/config
github.com/prometheus/prometheus/vendor/github.com/prometheus/client_model/go
github.com/prometheus/prometheus/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/awsutil
github.com/prometheus/prometheus/vendor/github.com/go-openapi/swag
github.com/prometheus/prometheus/vendor/golang.org/x/text/language
github.com/prometheus/prometheus/vendor/golang.org/x/text/unicode/bidi
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/expfmt
github.com/prometheus/prometheus/vendor/golang.org/x/text/unicode/norm
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/request
github.com/prometheus/prometheus/util/httputil
github.com/prometheus/prometheus/vendor/github.com/go-openapi/jsonpointer
github.com/prometheus/prometheus/vendor/golang.org/x/text/runes
github.com/prometheus/prometheus/vendor/golang.org/x/text/secure/bidirule
github.com/prometheus/prometheus/vendor/github.com/emicklei/go-restful/swagger
github.com/prometheus/prometheus/vendor/golang.org/x/text/width
github.com/prometheus/prometheus/vendor/github.com/gogo/protobuf/proto
github.com/prometheus/prometheus/vendor/github.com/gogo/protobuf/sortkeys
github.com/prometheus/prometheus/vendor/github.com/prometheus/client_golang/prometheus
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/client
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/corehandlers
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol/rest
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol/query/queryutil
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol/xml/xmlutil
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/ec2metadata
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/credentials/endpointcreds
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/waiter
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/signer/v4
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds
github.com/prometheus/prometheus/vendor/github.com/google/gofuzz
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol/query
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query
github.com/prometheus/prometheus/vendor/golang.org/x/text/cases
github.com/prometheus/prometheus/vendor/github.com/spf13/pflag
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/defaults
github.com/prometheus/prometheus/vendor/gopkg.in/inf.v0
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/third_party/forked/golang/reflect
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/sts
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/service/ec2
github.com/prometheus/prometheus/vendor/golang.org/x/text/secure/precis
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/conversion
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/fields
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/version
github.com/prometheus/prometheus/discovery/consul
github.com/prometheus/prometheus/discovery/file
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/sets
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/validation
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/conversion/queryparams
github.com/prometheus/prometheus/vendor/github.com/PuerkitoBio/purell
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/errors
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/types
github.com/prometheus/prometheus/vendor/github.com/aws/aws-sdk-go/aws/session
github.com/prometheus/prometheus/vendor/golang.org/x/net/http2/hpack
github.com/prometheus/prometheus/vendor/golang.org/x/net/lex/httplex
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/wait
github.com/prometheus/prometheus/vendor/github.com/go-openapi/jsonreference
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/labels
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/validation/field
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/json
github.com/prometheus/prometheus/vendor/github.com/go-openapi/spec
github.com/prometheus/prometheus/vendor/github.com/ghodss/yaml
github.com/prometheus/prometheus/vendor/github.com/ugorji/go/codec
github.com/prometheus/prometheus/vendor/golang.org/x/net/http2
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/framer
github.com/prometheus/prometheus/vendor/github.com/davecgh/go-spew/spew
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/util
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/schema
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/yaml
github.com/prometheus/prometheus/vendor/github.com/docker/distribution/digest
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/version
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime
github.com/prometheus/prometheus/vendor/k8s.io/client-go/tools/metrics
github.com/prometheus/prometheus/vendor/k8s.io/client-go/util/cert
github.com/prometheus/prometheus/vendor/github.com/juju/ratelimit
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/diff
github.com/prometheus/prometheus/vendor/github.com/docker/distribution/reference
github.com/prometheus/prometheus/vendor/k8s.io/client-go/util/flowcontrol
github.com/prometheus/prometheus/discovery/marathon
github.com/prometheus/prometheus/discovery/triton
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/util/parsers
github.com/prometheus/prometheus/vendor/github.com/samuel/go-zookeeper/zk
github.com/prometheus/prometheus/relabel
github.com/prometheus/prometheus/discovery/azure
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/openapi
github.com/prometheus/prometheus/vendor/github.com/opentracing/opentracing-go/log
github.com/prometheus/prometheus/storage
github.com/prometheus/prometheus/discovery/dns
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/api/resource
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/intstr
github.com/prometheus/prometheus/vendor/github.com/opentracing/opentracing-go
github.com/prometheus/prometheus/storage/metric
github.com/prometheus/prometheus/storage/local/codable
github.com/prometheus/prometheus/storage/local/chunk
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer/recognizer
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf
github.com/prometheus/prometheus/vendor/k8s.io/client-go/tools/clientcmd/api
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/util
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/comparer
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/storage
github.com/prometheus/prometheus/util/treecache
github.com/prometheus/prometheus/vendor/github.com/golang/snappy
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/cache
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/filter
github.com/prometheus/prometheus/util/flock
github.com/prometheus/prometheus/util/testutil
github.com/prometheus/prometheus/discovery/zookeeper
github.com/prometheus/prometheus/util/stats
github.com/prometheus/prometheus/vendor/golang.org/x/time/rate
github.com/prometheus/prometheus/vendor/github.com/opentracing/opentracing-go/ext
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/opt
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/util/net
github.com/prometheus/prometheus/vendor/github.com/julienschmidt/httprouter
github.com/prometheus/prometheus/vendor/github.com/opentracing-contrib/go-stdlib/nethttp
github.com/prometheus/prometheus/web/ui
github.com/prometheus/prometheus/vendor/golang.org/x/net/netutil
github.com/prometheus/prometheus/util/cli
github.com/prometheus/prometheus/util/promlint
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/errors
github.com/prometheus/prometheus/vendor/github.com/prometheus/common/route
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/iterator
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/journal
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/watch
github.com/prometheus/prometheus/vendor/k8s.io/client-go/transport
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/table
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb/memdb
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/apis/meta/v1
github.com/prometheus/prometheus/vendor/github.com/syndtr/goleveldb/leveldb
github.com/prometheus/prometheus/discovery/gce
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/api/errors
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured
github.com/prometheus/prometheus/vendor/k8s.io/client-go/rest/watch
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authentication
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authorization
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/certificates
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/policy
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/rbac
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/storage
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/storage/v1
github.com/prometheus/prometheus/storage/local/index
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authentication/v1
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/api/meta
github.com/prometheus/prometheus/storage/local
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/apimachinery
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/apimachinery/registered
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/apimachinery/announced
github.com/prometheus/prometheus/promql
github.com/prometheus/prometheus/storage/remote
github.com/prometheus/prometheus/discovery/ec2
github.com/prometheus/prometheus/template
github.com/prometheus/prometheus/storage/fanin
github.com/prometheus/prometheus/cmd/promtool
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authentication/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authorization/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authorization/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/certificates/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/policy/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/rbac/v1alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/rbac/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/storage/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/apimachinery/pkg/runtime/serializer
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/autoscaling
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/extensions
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/batch
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/settings
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authentication/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/authorization/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/certificates/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/policy/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/rbac/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/storage/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/apps
github.com/prometheus/prometheus/vendor/k8s.io/client-go/rest
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/apps/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/autoscaling/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/autoscaling/v2alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/batch/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/extensions/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/settings/v1alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/api/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/settings/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/discovery
github.com/prometheus/prometheus/vendor/k8s.io/client-go/tools/cache
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/batch/v2alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/autoscaling/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/apps/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/batch/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/scheme
github.com/prometheus/prometheus/vendor/k8s.io/client-go/pkg/apis/extensions/install
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/authentication/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/authentication/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/authorization/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/authorization/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/autoscaling/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/autoscaling/v2alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/batch/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/batch/v2alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/certificates/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/core/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/extensions/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/policy/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/rbac/v1alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/rbac/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/settings/v1alpha1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/storage/v1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes/typed/storage/v1beta1
github.com/prometheus/prometheus/vendor/k8s.io/client-go/kubernetes
github.com/prometheus/prometheus/discovery/kubernetes
github.com/prometheus/prometheus/discovery
github.com/prometheus/prometheus/notifier
github.com/prometheus/prometheus/retrieval
github.com/prometheus/prometheus/rules
github.com/prometheus/prometheus/web/api/v1
github.com/prometheus/prometheus/web
github.com/prometheus/prometheus/cmd/prometheus
tsurumah ~/go>ls bin/
prometheus*  promtool*
tsurumah ~/go>env GOPATH=`pwd` GO15VENDOREXPERIMENT=1 go test github.com/prometheus/prometheus/cmd/...
ok  	github.com/prometheus/prometheus/cmd/prometheus	0.156s
?   	github.com/prometheus/prometheus/cmd/promtool	[no test files]
```

**Comment by juliusv** [comment]
Nice!
