### ISSUE TITLE
go getting prometheus fails on arm

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#2926]
Just tried to go get prometheus on a raspberry pi 2 but it fails:

```
$ go get github.com/prometheus/prometheus/cmd/...
...
# github.com/prometheus/prometheus/util/promlint
go/src/github.com/prometheus/prometheus/util/promlint/promlint.go:86: undefined: sort.SliceStable
# github.com/prometheus/prometheus/web
go/src/github.com/prometheus/prometheus/web/web.go:386: undefined: sort.Slice
```

**Comment by grobie** [comment]
That's not related to ARM. Your golang version is too old, Prometheus requires go1.8+.

**Comment by discordianfish** [comment]
Hrm thought that happened after I upgraded to 1.8.3, but looks you're right. Thanks!
