### ISSUE TITLE
Commit 947c83b... breaks with go1.6 

### ISSUE THREAD

**Issue by jayeye** [prometheus/prometheus#2584]
I tried building from master (5f764d9...) on a machine with go1.6 (the default for ubuntu server 16.04), and got 

    # github.com/prometheus/prometheus/web
    go/src/github.com/prometheus/prometheus/web/web.go:383: undefined: sort.Slice 

I knew I had successfully built in v1.5.2 (bd1182d...). `git bisect` is my second-best friend, and shows me that the offending commit is 947c83b..., which according to the log followed shortly after an upgrade to go1.8 (5f764d9... builds fine with go1.8). 

If compatibility with older versions of go is required, maybe someone should look into this before the next release is cut.

**Comment by Gouthamve** [comment]
It has been explicitly decided that we break compat with 1.6.
See: https://github.com/prometheus/prometheus/pull/2548#discussion_r109044015 and https://github.com/prometheus/prometheus/pull/2548#issuecomment-290560081

**Comment by brian-brazil** [comment]
Yes, we worry about compat for client_golang but not anything else.
